project_id = "bohuglednqirnaearrkj"

[functions.public-scan-attendance]
verify_jwt = false

[functions.mayar-webhook]
verify_jwt = false

[functions.create-mayar-payment]
verify_jwt = false

[functions.admin-approve-payment]
verify_jwt = false

[functions.manage-mayar-key]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.create-user]
verify_jwt = false