project_id = "mtertpzbuhwlikzpzmvs"

[functions.seed-demo]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.public-monitoring]
verify_jwt = false

[functions.public-pickup]
verify_jwt = false

[functions.create-mayar-payment]
verify_jwt = false

[functions.mayar-webhook]
verify_jwt = false

[functions.lookup-npsn]
verify_jwt = false