project_id = "bohuglednqirnaearrkj"

[functions.public-scan-attendance]
verify_jwt = false

[functions.mayar-webhook]
verify_jwt = false

[functions.create-mayar-payment]
verify_jwt = false

[functions.admin-approve-payment]
verify_jwt = false

[functions.manage-mayar-key]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.referral]
verify_jwt = false

[functions.forgot-password]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp-reset]
verify_jwt = false

[functions.trial-check]
verify_jwt = false

[functions.mpwa-qr]
verify_jwt = false

[functions.mpwa-proxy]
verify_jwt = false

[functions.parent-portal]
verify_jwt = false